// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8v-bKF6sFUedc7j3LpFLBiIEMUn_FpSY',
    appId: '1:760673124560:web:d9ad87ad48f919ef415ed5',
    messagingSenderId: '760673124560',
    projectId: 'projectx-c2b3a',
    authDomain: 'projectx-c2b3a.firebaseapp.com',
    databaseURL: 'https://projectx-c2b3a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectx-c2b3a.firebasestorage.app',
    measurementId: 'G-1GSD8B1QZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0F0ZAtj1iAQrk8BV5sWZ3JYpV9M2ZQ4',
    appId: '1:760673124560:android:32af6f551af4ccb0415ed5',
    messagingSenderId: '760673124560',
    projectId: 'projectx-c2b3a',
    databaseURL: 'https://projectx-c2b3a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectx-c2b3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkef-BAUlpqNvHDcHLaCYpPUwWl8IImOc',
    appId: '1:760673124560:ios:32c3ceaa4c3344d8415ed5',
    messagingSenderId: '760673124560',
    projectId: 'projectx-c2b3a',
    databaseURL: 'https://projectx-c2b3a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectx-c2b3a.firebasestorage.app',
    iosBundleId: 'com.wilson.projectx.projectx',
  );
}
